[package]
name = "sentry-contrib-native"
version = "0.1.0"
authors = ["daxpedda <daxpedda@gmail.com>"]
edition = "2018"

[workspace]
members = ["sentry-contrib-native-sys"]

[dependencies]
http = { version = "0.2", optional = true }
once_cell = "1"
rmpv = "0.4"
sys = { package = "sentry-contrib-native-sys", path = "sentry-contrib-native-sys", default-features = false }
thiserror = "1"
url = { version = "2.1", optional = true }
vsprintf = { git = "https://github.com/daxpedda/vsprintf", branch = "fix-windows" }

[dev-dependencies]
anyhow = "1"
rusty-fork = { git = "https://github.com/daxpedda/rusty-fork", branch = "proc-macro-feature", features = [
  "macro"
] }

# Used by the custom-transport example.
parking_lot = "0.11"
reqwest = { version = "0.10", default-features = false, features = [
  "rustls-tls"
] }
tokio = { version = "0.2", features = ["rt-threaded"] }

[features]
default = ["default-transport"]
default-transport = ["sys/default-transport"]
custom-transport = ["http", "url"]
nightly = []
test = []

[[example]]
name = "custom-transport"
required-features = ["custom-transport"]
