[package]
name = "sentry-contrib-native-sys"
version = "0.1.0"
authors = ["daxpedda <daxpedda@gmail.com>"]
edition = "2018"
links = "sentry-native"

[build-dependencies]
anyhow = "1"
cmake = "0.1"

[dependencies]
va_list = "0.1"

[features]
default = ["default-transport"]
default-transport = []
